Feature integration test & fix n+1
lincoln1883/blog-app pull request #9
Opened 2023-08-30 02:03 UTC by lincoln1883

For this milestone we completed the following task:
- [ ] n + 1
  - [ ] Make sure that the N+1 problem is solved when fetching all posts and their comments for a user.
  - [ ] In your PR description include the screenshots of your app's logs before and after the fix
   - before eager-loading.
 
   ![Screenshot from 2023-08-29 10-32-42](https://github.com/lincoln1883/blog-app/assets/84746035/c89e0776-f8f7-451b-a847-aef4d2c007ec)
 - after implementing eager-loading
 
   ![Screenshot from 2023-08-29 10-55-08](https://github.com/lincoln1883/blog-app/assets/84746035/7d6de30a-ca88-403a-9069-c66d7e0931d3)

- [ ] Integration specs.
- [ ] Use Capybara to write integration tests for each view in your project.
  - [ ] User index page:
    - I can see the username of all other users.
    - I can see the profile picture for each user.
    - I can see the number of posts each user has written.
    - When I click on a user, I am redirected to that user's show page.
  - [ ] user show page:
    - I can see the user's profile picture.
    - I can see the user's username.
    - I can see the number of posts the user has written.
    - I can see the user's bio.
    - I can see the user's first 3 posts.
    - I can see a button that lets me view all of a user's posts.
    - When I click a user's post, it redirects me to that post's show page.
    - When I click to see all posts, it redirects me to the user's post's index page.
  - [ ] User post index page:
    - I can see the user's profile picture.
    - I can see the user's username.
    - I can see the number of posts the user has written.
    - I can see a post's title.
    - I can see some of the post's body.
    - I can see the first comments on a post.
    - I can see how many comments a post has.
    - I can see how many likes a post has.
    - I can see a section for pagination if there are more posts than fit on the view.
    - When I click on a post, it redirects me to that post's show page.
  - [ ] Post show page:
    - I can see the post's title.
    - I can see who wrote the post.
    - I can see how many comments it has.
    - I can see how many likes it has.
    - I can see the post body.
    - I can see the username of each commenter.
    - I can see the comment each commentor left.

2023-08-30 02:07 UTC, Reem-lab commented
Hello @lincoln1883 could you check your slack?

2023-08-30 02:41 UTC, FrederickMih reviewed
## Hi :raising_hand: :raising_hand: @, 


While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

This is a pair-programming activities. You are kindly reminded to work with your peer and later on request for review individually. In the commit history, everyone should contribute equally :+1: 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-08-30 16:26 UTC, TadesseDev requested changes
### Hi Team

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![212094426-b41dd457-c9db-4ab3-bbe9-176dd8dd08b7](https://user-images.githubusercontent.com/69077061/212385281-4797c58a-d358-423a-aa7c-832c22203865.gif)




## Highlights
 - [x] You have written a clean code ✅
 - [x]  Most of the requirement has been meet. ✅

 
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-30 16:26 UTC, TadesseDev commented on spec/system/users_index_pages_spec.rb
> +    end
- [ ] Dear Team, Please be reminded here we are testing for a number of users instead of just one. Hence we need to have more than one user and test the ` username of all other users, profile picture for each user, number of posts each user has written`.  This way we can assert the application behaves as expected while working with multiple users.

2023-08-30 16:26 UTC, TadesseDev commented on spec/system/users_show_page_spec.rb
> +end
- [ ] Dear Team, I notice you are missing some tests for the `user_show` routes. Please add the following tests. 

### Missing tests
![Screen Shot 2023-08-30 at 7 15 39 PM](https://github.com/lincoln1883/blog-app/assets/69077061/d5208e9d-aea8-4920-9ece-66050f54430e)

2023-08-30 16:26 UTC, TadesseDev commented on spec/system/post_index_pages_spec.rb
> +      visit user_posts_path(user.id)
- [ ] Also here you are missing one test, which is a test `Tests that asserts you can see the first comments on a post.` Please consider adding this one.

2023-08-30 16:26 UTC, TadesseDev commented on spec/system/posts_show_pages.rb
> +    end
- [Optional] I believe this test belongs to the `users _show` page, some of these tests are missing in the `users _show` page where I mark them as required changes.

2023-08-30 22:38 UTC, laiifuu requested changes
# STATUS: CHANGES REQUIRED :recycle: 

## Hi @lincoln1883 :wave: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![giphy](https://user-images.githubusercontent.com/93520178/261856992-3a2ad29c-e181-4e1b-bf50-a98ee69c28da.gif)

 ## Highlights
- [x] Some of the changes required were implemented :+1: 

 ## Required Changes ♻️
_Check the comments under the review :point_down:_

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and :computer: Happy coding :computer: 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-30 22:38 UTC, laiifuu commented on spec/system/users_index_pages_spec.rb
> +      expect(page).to have_content(user.posts_counter)
As mentioned by the previous reviewer, you should be testing for multiple users, not just one. 
Also when running both these tests I got the following error: 
![image](https://github.com/lincoln1883/blog-app/assets/93520178/bd30e5c9-de87-4c6e-a564-6a65f30e5568)
This is because `User.all` returns an array, and you're using that array as if it was a single user object. 
You should start by having multiple users (at least 2), then add the tests requested by the previous reviewer (`test the  username of all other users, profile picture for each user, number of posts each user has written`)

2023-08-30 22:38 UTC, laiifuu commented on spec/system/post_index_pages_spec.rb
> +    end
As mentioned by the previous reviewer, you should have tests that assert you can see the first comments on a post. You should start by creating multiple comments first then test on them. Also there's a repetition from line 3 to line 35, all those lines give the same result.

2023-08-31 02:28 UTC, t-yanick requested changes
# STATUS: CHANGES REQUIRED

Hi @lincoln1883 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-31 02:28 UTC, t-yanick commented on spec/system/users_index_pages_spec.rb
> +    user = User.create(name: 'Test User', bio: 'it me again', photo: 'https://picsum.photos/200/300', posts_counter: 1)
- [ ] Hi Team, I don't think you have implemented the requested changes by the previous reviewers. You have been asked to create multiple users. At the moment you have just one user created. Below is a quotation from the last reviewer.
`You should start by having multiple users (at least 2), then add the tests requested by the previous reviewer (test the  username of all other users, profile picture for each user, number of posts each user has written)`

2023-08-31 02:28 UTC, t-yanick commented on spec/system/post_index_pages_spec.rb
> +    let!(:comment) { post.comments.create(text: 'Test Comment', post_id: post.id, author_id: user.id) }
- [ ] Hi Team, as requested by the last reviewer, you should start by creating multiple comments, then make the tests on the comments created. Below is a quotation from the last reviewer.
`As mentioned by the previous reviewer, you should have tests that assert you can see the first comments on a post. You should start by creating multiple comments first then test on them`

2023-08-31 02:28 UTC, t-yanick commented on spec/system/post_index_pages_spec.rb
> +      expect(page).to have_content(comment.text)
- [ ] Hi team, It seems you did not make any changes as per the last reviewer's requests. Lines 33 to 35 are still repeating. Kindly delete the repeating lines (lines 34 and 35)

2023-08-31 03:28 UTC, lincoln1883 commented on spec/system/post_index_pages_spec.rb
> +      expect(page).to have_content(comment.text)
There was a huge misunderstanding arising from the first CR who asked to rename the branch, and so I did and everything went sideways from there.

2023-08-31 03:54 UTC, t-yanick approved these changes
# STATUS: MILESTONE APPROVED :1st_place_medal: 

Hi @lincoln1883 , 

### Great job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Requested changes implemented 👍 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-31 04:04 UTC, merged